---
- name: Add Helm repository for Traefik
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://traefik.github.io/charts

- name: Deploy Traefik Helm chart
  kubernetes.core.helm:
    name: "{{ traefik_release_name }}"
    update_repo_cache: true
    chart_ref: traefik/traefik
    chart_version: "{{ traefik_chart_version }}"
    release_namespace: "{{ traefik_namespace }}"
    create_namespace: true
    values:
      "{{ traefik_values }}"
