---
home_assistant_chart_version: 0.3.31

home_assistant_values:
  controller:
    type: StatefulSet
  persistence:
    enabled: true
    size: 1Gi
    annotations:
      k8up.io/backup: "true"
  additionalVolumes:
    - hostPath:
        path: >-
          /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2695656-if00
        type: CharDevice
      name: zigbee
  additionalMounts:
    - mountPath: /dev/ttyACM0
      name: zigbee
  ingress:
    enabled: true
    external: false
    hosts:
      - host: "{{ hostname }}"
        paths:
          - path: "/home-assistant"
            pathType: Prefix
  hostPort:
    enabled: true
    port: 8124
  securityContext:
    privileged: true
  serviceMonitor:
    enabled: false
    scrapeInterval: 60s
  env:
    - name: MY_TIME_ZONE
      value: "Europe/Berlin"

